### ISSUE TITLE
Not displaying fzf menu

### ISSUE THREAD

**Issue by gtmtech** [JKubovy/fzf-wrapper#1]
I'm on macosx M1 Monterey (12.4) Using terminal, bash and python 3.9.13

When using your module, even just doing the most basic demo task, when it invokes fzf, I dont see anything on screen. 

The reason is this line:

```
    command_result = run(command, input=choices_bytes, stderr=PIPE, stdout=PIPE)
```

fzf dumps all its information on stderr - and you are trying to handle stderr so it doesnt get displayed. 

If I comment out stderr=PIPE then it works. I dont think you should need anything from stderr.

**Comment by JKubovy** [comment]
If I don't use PIPE on stderr, I won't be able to read any errors. It's interesting that in Python 3.7 it works as expected (windows and linux), but now that I tried it on 3.10, it doesn't. I guess they changed/fixed something in Python 3.9+.
I'll have to take a look at how I could change it to make the wrapper work, but at the same time to get at any bugs.

**Comment by therealmaxmoon** [comment]
Any solution yet? Because I have the exact same problem, that fzf will not show a selection menu.

**Comment by JKubovy** [comment]
Can you test new version 0.1.7 and let me know if it works now?

**Comment by therealmaxmoon** [comment]
It works now!

Thanks for the quick fix.

**Comment by therealmaxmoon** [comment]
... but I just figured out that `prompt` returns a list and not a string.

At least I would expect to get a string back if I give it a list of strings, like your exmple:

`prompt(['one', 'two', 'three'])`

**Comment by JKubovy** [comment]
You can see it in the gif and it's done that intentionally. When you call the prompt function, exactly three things can happen. The call will throw a `ValueError` exception if you as the programmer call the function with the wrong parameters, an `AttributeError` exception if there is some problem with fzf (not installed or ended up incorrectly), or the function will return a list of strings. An empty list means the user hasn't selected anything, and a non-empty list contains the user's selection (with the --multi switch, the user can select multiple items).

If you know that the call will always return the result as a list of strings, you are not likely to make a mistake in processing the result.

The intended use is as follows:
```python
try:
    result = prompt(['one', 'two', 'three'], '--multi')
    if (len(result) == 0):
        print('The user has not selected anything')
    elif (len(result) == 1):
        print(f'User choose: {result[0]}')
    else:
        print(f'User choose {len(result)} items')
except ValueError:
    print('Sorry my bad! I called prompt with wrong parameters')
except AttributeError as e:
    print('There is a problem with fzf call')
    print(e)
```

**Comment by therealmaxmoon** [comment]
Oh, that's right! I forgot about the multi switch.

Thank you.
